name: Build_deploy

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_deploy_with_npm:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: npm install

      - name: Build for production
        run: CI= npm run build
      
      - name: Files list
        run: ls && ls build/

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "html/${GITHUB_REF##*/}"
