name: Build_deploy

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_deploy_with_npm:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: npm install

      - name: Set backend env
        run: (echo "${GITHUB_REF##*/}" | grep -Eq  '^(develop)|(predev)$' ) && (echo "SUBDOMAIN=${GITHUB_REF##*/}." >> $GITHUB_ENV ) || echo "Standart"

      - name: Build for production
        run: REACT_APP_BACKEND=http://${SUBDOMAIN}nl-mail.ru CI= npm run build
      
      - name: Files list
        run: ls && ls build/

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "html/${GITHUB_REF##*/}"